#!/bin/bash

mkdir build/
make
chmod +x build/main

echo -e "#!/bin/bash\ncd $PWD\n ./build/main " > /usr/bin/jveh
cat CLI/jvehExtra.txt >> /usr/bin/jveh
cp CLI/jveh.1.gz /usr/share/man/man1/jveh.1.gz

chmod +x /usr/bin/jveh
chmod +x uninstall